name: Run Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Run Coverage
        run: npx hardhat coverage

      - name: View Coverage Summary
        id: view_coverage
        run: |
          echo "Coverage Summary:"
          lcov --list ./coverage/lcov.info

      - name: Output Coverage Table
        run: |
          echo "Coverage Table:"
          lcov --list ./coverage/lcov.info | column -t
